- name: deploy
  become: true
  hosts: slave
  vars_files:
    - vars/main.yml
  roles:
    # - setup
      #- apache2
      # - php
      #- composer
      #- geerlingguy.mysql
      #- pgsql
    - deploy
    
